pipeline {
    agent any

    stages {


        stage('Setup') {
            steps {

                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r Jenkins_basic/requirements.txt
                '''            


            }
       }
        stage('Test') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest
                '''
                
            }
        }    
        stage('Deployment') {
            input {
                message "Do you want to proceed further?"
                ok "Yes"
            }
            steps {
                echo "Running Deployment"
                
            }
        } 
        
            
    }
}
