pipeline {
    agent any

    stages {
        // Stage 1: Setup virtual environment and install dependencies
        stage('Setup') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r Jenkins_basic/requirements.txt
                '''
            }
        }

        // Stage 2: Run tests
        stage('Test') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest
                '''
            }
        }

       
    }
}
